### ISSUE TITLE
Shows custom posts archive in selected page instead page content

### ISSUE THREAD

**Issue by tyrann0us** [humanmade/page-for-post-type#14]
In #9, @fabienlege writes that he expected the loop to automatically run on the page.
@codepuncher responds:

> This is just to let users choose a page to act as the relating archive to the post type. This means you can put anything on this page.

Strange thing is: On two test projects of mine the `archive.php` template _is_ used, displaying the post loop. This is the opposite of what @codepuncher und @roborourke claim. Am I right that the page should display it's content? If yes, why does it display the custom post type archive for me?

Note that I need to manually flush rewrite rules by clicking "Save changes" on "Settings" -> "Permalinks" to make this happen.

My setup:
PHP v7.1.12
WordPress v4.9.6 (based on [Bedrock](https://roots.io/bedrock/))
Theme: Twenty Seventeen
No other plugins active (execpt self coded plugin to register custom post type)

Any suggestions how to fix this is highly appreciated! Thanks!

**Comment by tyrann0us** [comment]
https://github.com/humanmade/page-for-post-type/blob/b603f30fea65328002789dffd73cf7ef2030ecbb/page-for-post-type.php#L251

@roborourke, if I understand this line correctly, it tells WordPress to display the post type archive instead of the default page content, right? So why doesn't this apply to @fabienlege and @codepuncher? And wouldn't it be useful to let the user disable this?

Then there's this:
`$args->has_archive` is always set to `$slug` (string):
https://github.com/humanmade/page-for-post-type/blob/b603f30fea65328002789dffd73cf7ef2030ecbb/page-for-post-type.php#L238

so `$args->has_archive` will never be `true`:
https://github.com/humanmade/page-for-post-type/blob/b603f30fea65328002789dffd73cf7ef2030ecbb/page-for-post-type.php#L244

I doubt this is related to the issue but still it confuses me ...

Any feedback on this is highly appreciated! Thanks!

**Comment by tyrann0us** [comment]
Hi @roborourke, [now that you are back](https://github.com/humanmade/page-for-post-type/issues/17#issuecomment-728922426), maybe you could take a look at this? I haven't tested the plugin in a while, but had the need for something similar multiple times in the past. It never worked for me.
Thanks!

**Comment by roborourke** [comment]
So that is the intended behaviour - it modifies the query on that page URL to be the archive so it wouldn’t use the page template. If you had a post type archive template it would use that. I think I just didn’t explain clearly. You can use the `get_page_for_post_type()` function to get the page ID and access the page content or data that way. This was mainly aimed at making it easier to nest the post type archive page in nav menus or the page hierarchy and better control the site structure.
