### ISSUE TITLE
Add a composer.json

### ISSUE THREAD

**Issue by jonginn** [humanmade/page-for-post-type#5]
Amazing simple plugin, and it's now an essential part of my WP stack.

Would it be possible for you to add a `composer.json` and register the package on [Packagist](https://packagist.org/), so that the plugin can be called in with Composer?

I would also recommend you include `wordpress-plugin` in the `type` field.

If you'd prefer, I could give you a pull request for the `composer.json` file but someone at Human Made should be the one to add it to Packagist so you can control it on that end.

**Comment by chrisnx** [comment]
+1

**Comment by JacobDB** [comment]
Looks like this was added at some point a few years back, but I can't seem to get it to actually work...
