### ISSUE TITLE
Is it possible to include this in a theme?

### ISSUE THREAD

**Issue by JacobDB** [humanmade/page-for-post-type#8]
I'd like to just include this code in my starter theme files, but I can't seem to get it working. Any tips on how to make this work?

**Comment by JacobDB** [comment]
Figured this out, I just needed to change the hook to `after_theme_setup`

**Comment by berend-de-jong** [comment]
Or add `Page_For_Post_Type::get_instance();` underneath the manual inclusion. Then you won't need to edit the plugin files.
